build: Problema1.class Problema2.class

Problema1.class: Problema1.java
	javac Problema1.java

Problema2.class: Problema2.java
	javac Problema2.java

run-p1:
	java Problema1

run-p2:
	java Problema2

clean:
	rm -f *.class
