build: Problema1.class Prob2.class

Problema1.class: Problema1.java
	javac Problema1.java

Prob2.class: Prob2.java
	javac Prob2.java

run-p1:
	java Problema1

run-p2:
	java Prob2

clean:
	rm -f *.class
